# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.provisionerName: "rawfile.csi.openebs.io"

defaults: &defaults
  image:
    repository: ghcr.io/canonical/rawfile-localpv
    tag: 0.8.2
    pullPolicy: Always
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi

controller:
  <<: *defaults
  csiDriverArgs:
    - --args
    - rawfile
    - csi-driver
    - --disable-metrics

images:
  csiNodeDriverRegistrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
  csiProvisioner: registry.k8s.io/sig-storage/csi-provisioner:v5.0.2
  csiResizer: registry.k8s.io/sig-storage/csi-resizer:v1.11.2
  csiSnapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v8.0.2

node:
  <<: *defaults
  storage:
    path: /var/csi/rawfile
  metrics:
    enabled: false
  nodeSelector:
    storageType: "fast"

storageClass:
  enabled: true
  name: "csi-rawfile"
  isDefault: false
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

imagePullSecrets: []
serviceMonitor:
  enabled: false
  interval: 1m
